// Runtime configuration loaded from /config.js
// In production, this is generated by docker-entrypoint.sh
// In development, this falls back to import.meta.env

declare global {
    interface Window {
        ENV?: {
            VITE_API_BASE_URL?: string;
            VITE_ADMIN_KEY?: string;
            VITE_DEVICE_KEY?: string;
            VITE_OIDC_ENABLED?: string;
            VITE_OIDC_AUTHORITY?: string;
            VITE_OIDC_CLIENT_ID?: string;
            VITE_OIDC_REDIRECT_URI?: string;
            VITE_OIDC_SCOPE?: string;
        };
    }
}

type EnvKey = 'VITE_API_BASE_URL' | 'VITE_ADMIN_KEY' | 'VITE_DEVICE_KEY' |
              'VITE_OIDC_ENABLED' | 'VITE_OIDC_AUTHORITY' | 'VITE_OIDC_CLIENT_ID' |
              'VITE_OIDC_REDIRECT_URI' | 'VITE_OIDC_SCOPE';

function getEnv(key: EnvKey): string {
    // Try runtime config first (production)
    if (window.ENV && window.ENV[key]) {
        return window.ENV[key] as string;
    }

    // Fall back to build-time env (development)
    return import.meta.env[key] || '';
}

export const runtimeConfig = {
    get API_BASE_URL() {
        return getEnv('VITE_API_BASE_URL');
    },
    get ADMIN_KEY() {
        return getEnv('VITE_ADMIN_KEY');
    },
    get DEVICE_KEY() {
        return getEnv('VITE_DEVICE_KEY');
    },
    get OIDC_ENABLED() {
        return getEnv('VITE_OIDC_ENABLED') === 'true';
    },
    get OIDC_AUTHORITY() {
        return getEnv('VITE_OIDC_AUTHORITY');
    },
    get OIDC_CLIENT_ID() {
        return getEnv('VITE_OIDC_CLIENT_ID');
    },
    get OIDC_REDIRECT_URI() {
        return getEnv('VITE_OIDC_REDIRECT_URI') || window.location.origin;
    },
    get OIDC_SCOPE() {
        return getEnv('VITE_OIDC_SCOPE') || 'openid profile email';
    }
};
